// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENtVOIPtYvt-FLfrIyK-PRem4ZICp-NY',
    appId: '1:1016962666124:web:a4805173c66bf9be0c75a9',
    messagingSenderId: '1016962666124',
    projectId: 'volley-score-f5058',
    authDomain: 'volley-score-f5058.firebaseapp.com',
    storageBucket: 'volley-score-f5058.firebasestorage.app',
    measurementId: 'G-702BQ1SFF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgux2o7vX3e9PuOty3St-RL5GmYcbLac',
    appId: '1:1016962666124:android:f0cfe78f24cd96a00c75a9',
    messagingSenderId: '1016962666124',
    projectId: 'volley-score-f5058',
    storageBucket: 'volley-score-f5058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUoFEhr_3OEUb7d5whN0pN4JYORtwSDU',
    appId: '1:1016962666124:ios:bbbe6ddf302a5a130c75a9',
    messagingSenderId: '1016962666124',
    projectId: 'volley-score-f5058',
    storageBucket: 'volley-score-f5058.firebasestorage.app',
    iosBundleId: 'com.example.volleyScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPUoFEhr_3OEUb7d5whN0pN4JYORtwSDU',
    appId: '1:1016962666124:ios:bbbe6ddf302a5a130c75a9',
    messagingSenderId: '1016962666124',
    projectId: 'volley-score-f5058',
    storageBucket: 'volley-score-f5058.firebasestorage.app',
    iosBundleId: 'com.example.volleyScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENtVOIPtYvt-FLfrIyK-PRem4ZICp-NY',
    appId: '1:1016962666124:web:b223b154702e95460c75a9',
    messagingSenderId: '1016962666124',
    projectId: 'volley-score-f5058',
    authDomain: 'volley-score-f5058.firebaseapp.com',
    storageBucket: 'volley-score-f5058.firebasestorage.app',
    measurementId: 'G-K7W76R7PGT',
  );
}
